import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:path/path.dart' as p;

import '../models/download_progress.dart';
import '../models/playlist_entry.dart';
import '../models/subtitle_settings.dart';
import '../models/video_metadata.dart';

/// Thin wrapper around the `yt-dlp` CLI. Pure Dart, no UI deps — safe to
/// unit-test by injecting a [_ProcessRunner] / [_ProcessSpawner].
///
/// Right now we shell out to whichever `yt-dlp` is on `PATH`. PR 8 will switch
/// this to a bundled binary that ships inside the app, so the user doesn't
/// need yt-dlp pre-installed.
class YtDlpService {
  YtDlpService({
    String executable = 'yt-dlp',
    Future<ProcessResult> Function(String, List<String>)? processRunner,
    Future<Process> Function(String, List<String>)? processSpawner,
  })  : _exe = executable,
        _runner = processRunner ?? _defaultRunner,
        _spawner = processSpawner ?? _defaultSpawner;

  final String _exe;
  final Future<ProcessResult> Function(String, List<String>) _runner;
  final Future<Process> Function(String, List<String>) _spawner;

  /// Run `yt-dlp --dump-single-json` to fetch metadata for a single URL.
  ///
  /// Throws [YtDlpException] if the process exits non-zero. The thrown
  /// message is yt-dlp's own stderr — that's more useful to surface than a
  /// paraphrase, e.g. "Sign in to confirm you're not a bot" or "Video
  /// unavailable in your country".
  Future<VideoMetadata> fetchMetadata(String url) async {
    if (url.trim().isEmpty) {
      throw YtDlpException('URL is empty.');
    }
    const args = <String>[
      '--dump-single-json',
      '--no-playlist',
      '--no-warnings',
    ];
    final fullArgs = [...args, url];

    final ProcessResult result;
    try {
      result = await _runner(_exe, fullArgs);
    } on ProcessException catch (e) {
      throw YtDlpException(
        'yt-dlp not found at "$_exe". Install it with `pip install yt-dlp` '
        'or apt/brew. Original error: ${e.message}',
      );
    }
    if (result.exitCode != 0) {
      final stderr = (result.stderr as String?)?.trim() ?? '';
      throw YtDlpException(
        stderr.isEmpty
            ? 'yt-dlp exited with code ${result.exitCode}.'
            : stderr,
      );
    }
    final stdout = result.stdout as String;
    try {
      final json = jsonDecode(stdout) as Map<String, dynamic>;
      return VideoMetadata.fromJson(url, json);
    } on FormatException catch (e) {
      throw YtDlpException(
        "Couldn't parse yt-dlp's JSON output: ${e.message}",
      );
    }
  }

  /// Run `yt-dlp --flat-playlist --dump-json` to list all entries in a
  /// playlist without downloading anything. Each line of stdout is a JSON
  /// object describing one video.
  ///
  /// Throws [YtDlpException] on failure.
  Future<List<PlaylistEntry>> fetchPlaylist(String url) async {
    if (url.trim().isEmpty) {
      throw YtDlpException('URL is empty.');
    }
    final args = <String>[
      '--flat-playlist',
      '--dump-json',
      '--no-warnings',
      url,
    ];

    final ProcessResult result;
    try {
      result = await _runner(_exe, args);
    } on ProcessException catch (e) {
      throw YtDlpException(
        'yt-dlp not found at "$_exe". Install it with `pip install yt-dlp` '
        'or apt/brew. Original error: ${e.message}',
      );
    }
    if (result.exitCode != 0) {
      final stderr = (result.stderr as String?)?.trim() ?? '';
      throw YtDlpException(
        stderr.isEmpty
            ? 'yt-dlp exited with code ${result.exitCode}.'
            : stderr,
      );
    }

    final stdout = result.stdout as String;
    final entries = <PlaylistEntry>[];
    for (final line in stdout.trim().split('\n')) {
      if (line.trim().isEmpty) continue;
      try {
        final json = jsonDecode(line) as Map<String, dynamic>;
        final entry = PlaylistEntry.fromJson(json);
        if (entry.url.isNotEmpty) entries.add(entry);
      } catch (_) {
        continue;
      }
    }
    return entries;
  }

  /// Run `yt-dlp --flat-playlist --print %(playlist_title)s` to get the
  /// playlist's own title. Used to seed the group-folder name in the
  /// Playlist tab so the user doesn't have to type it themselves.
  ///
  /// Returns `null` (rather than throwing) when yt-dlp emits no title — many
  /// non-YouTube playlists, "Mix" / autogenerated playlists, or single-video
  /// URLs simply don't have one. Callers should fall back to a default name.
  Future<String?> getPlaylistTitle(String url) async {
    if (url.trim().isEmpty) return null;
    final args = <String>[
      '--flat-playlist',
      '--print',
      '%(playlist_title|)s',
      '--no-warnings',
      // Some extractors print one line per entry even with --print; we only
      // need the first non-empty one.
      '--playlist-items',
      '1',
      url,
    ];
    final ProcessResult result;
    try {
      result = await _runner(_exe, args);
    } on ProcessException {
      return null;
    }
    if (result.exitCode != 0) return null;
    final stdout = (result.stdout as String?) ?? '';
    for (final line in stdout.split('\n')) {
      final t = line.trim();
      if (t.isNotEmpty && t != 'NA') return t;
    }
    return null;
  }

  /// Start an actual download. Returns a [DownloadHandle] you can listen to
  /// for [DownloadProgress] events and call [DownloadHandle.cancel] on.
  ///
  /// [outputExt] is the desired container/codec extension chosen by the user,
  /// e.g. 'mp4', 'mkv', 'mp3', 'm4a'. When [format] is audio-only the
  /// service switches to -x --audio-format mode automatically.
  ///
  /// [trimStart] / [trimEnd] are optional segment boundaries. When either is
  /// provided the service downloads to a hidden temp file first, then runs
  /// ffmpeg to cut the segment into the final file and deletes the temp.
  /// Requires ffmpeg on PATH.
  ///
  /// The returned stream completes (closes) once yt-dlp exits, regardless of
  /// success/failure/cancel. Listen for the terminal phase event and update
  /// UI state accordingly.
  DownloadHandle download({
    required VideoMetadata metadata,
    required VideoFormat format,
    required String outputDir,
    String outputExt = 'mp4',
    String outputTemplate = '%(title).200B [%(id)s].%(ext)s',
    String? customFilename,
    Duration? trimStart,
    Duration? trimEnd,
    String? rateLimit,
    bool keepPartial = false,
    SubtitleSettings? subtitles,
  }) {
    final controller = StreamController<DownloadProgress>.broadcast();
    final processCompleter = Completer<Process>();
    final state = _DownloadState();

    final bool isTrimming = trimStart != null || trimEnd != null;

    // yt-dlp handles audio-only differently from video:
    //   video: --merge-output-format <ext>  (remux after muxing streams)
    //   audio: -x --audio-format <ext>      (extract + transcode)
    // 'ogg' is a container not a codec — yt-dlp needs 'vorbis' internally.
    final bool isAudio = format.isAudioOnly;
    final String ytdlpAudioFmt = outputExt == 'ogg' ? 'vorbis' : outputExt;

    // When trimming we download to a temp file so ffmpeg can read it cleanly.
    // The temp name uses a fixed prefix so it can be found and deleted on error.
    final String effectiveTemplate;
    if (isTrimming) {
      effectiveTemplate = '_d4m_temp_${DateTime.now().millisecondsSinceEpoch}.%(ext)s';
    } else if (customFilename != null && customFilename.isNotEmpty) {
      effectiveTemplate = '${_sanitizeFilename(customFilename)}.%(ext)s';
    } else {
      effectiveTemplate = outputTemplate;
    }

    // Build subtitle-related flags. We only add them when the user has
    // explicitly enabled subtitles AND the language string is non-empty —
    // otherwise the SubtitleSettings.disabled instance is a no-op and yt-dlp
    // gets no extra flags. Embedding is only honoured for video output and
    // for containers that actually carry subs (MP4 / MKV); for everything
    // else the toggle quietly falls back to writing a sidecar file.
    final List<String> subtitleArgs;
    if (subtitles != null &&
        subtitles.enabled &&
        subtitles.language.trim().isNotEmpty) {
      final lang = subtitles.language.trim();
      final fmt = subtitles.format.trim().isEmpty
          ? 'srt'
          : subtitles.format.trim();
      final canEmbed = !isAudio && kEmbedSubsSupportedExts.contains(outputExt);
      subtitleArgs = <String>[
        '--write-subs',
        // Always include auto-subs as a fallback so videos without manual
        // subtitles still get auto-generated captions. Without this flag
        // playlist downloads are inconsistent — only videos with manually
        // uploaded subs would produce a transcript file.
        '--write-auto-subs',
        '--sub-langs', lang,
        '--sub-format', '$fmt/best',
        '--convert-subs', fmt,
        if (subtitles.embed && canEmbed) '--embed-subs',
        // Space out subtitle requests slightly to avoid rate-limiting when
        // downloading subtitles for many playlist items concurrently.
        '--sleep-subtitles', '1',
      ];
    } else {
      subtitleArgs = const <String>[];
    }

    final args = <String>[
      '--newline',
      '--no-playlist',
      '--no-warnings',
      '--no-cache-dir',
      '-f', format.id,
      if (isAudio) ...['-x', '--audio-format', ytdlpAudioFmt]
      else ...['--merge-output-format', outputExt],
      if (rateLimit != null && rateLimit.isNotEmpty) ...['--rate-limit', rateLimit],
      ...subtitleArgs,
      '-o', p.join(outputDir, effectiveTemplate),
      metadata.url,
    ];

    Future<void> run() async {
      Process process;
      try {
        process = await _spawner(_exe, args);
      } on ProcessException catch (e) {
        controller.add(
          DownloadProgress(
            phase: DownloadPhase.error,
            errorMessage: 'yt-dlp not found at "$_exe": ${e.message}',
          ),
        );
        await controller.close();
        processCompleter.completeError(e);
        return;
      }
      processCompleter.complete(process);

      controller.add(const DownloadProgress(phase: DownloadPhase.downloading));

      final stdoutSub = process.stdout
          .transform(utf8.decoder)
          .transform(const LineSplitter())
          .listen((line) {
        final progress = parseProgressLine(line);
        if (progress == null) return;
        if (progress.outputPath != null) {
          state.outputPath = progress.outputPath;
        }
        if (progress.percent != null) {
          state.lastPercent = progress.percent;
        }
        // Carry the paused flag through so the UI stays correct while
        // progress lines trickle in from the buffer during a pause.
        if (state.paused) {
          controller.add(DownloadProgress(
            phase: progress.phase,
            paused: true,
            percent: progress.percent,
            speedBytesPerSecond: null,
            eta: null,
            totalBytes: progress.totalBytes,
            outputPath: progress.outputPath,
            message: 'Paused',
          ));
        } else {
          controller.add(progress);
        }
      });

      // Give the handle a way to pause/resume the stdout subscription.
      // Pausing the subscription stops us reading from the pipe; the OS
      // buffer (~64 KB) fills up quickly and yt-dlp stalls by itself —
      // no SIGSTOP/SIGCONT, works identically on Windows, Linux, Android.
      state.pauseCallback  = () {
        stdoutSub.pause();
        controller.add(DownloadProgress(
          phase: DownloadPhase.downloading,
          paused: true,
          percent: state.lastPercent,
          message: 'Paused',
        ));
      };
      state.resumeCallback = () {
        stdoutSub.resume();
        controller.add(DownloadProgress(
          phase: DownloadPhase.downloading,
          paused: false,
          percent: state.lastPercent,
          message: 'Resuming…',
        ));
      };

      final stderrBuf = StringBuffer();
      final stderrSub = process.stderr
          .transform(utf8.decoder)
          .listen(stderrBuf.write);

      final code = await process.exitCode;
      await stdoutSub.cancel();
      await stderrSub.cancel();

      if (state.cancelled) {
        // Clean up any partial temp file, unless the user wants to keep it.
        if (!keepPartial) _deleteTempFile(state.outputPath);
        controller.add(const DownloadProgress(phase: DownloadPhase.cancelled));
        await controller.close();
        return;
      }

      if (code != 0) {
        if (!keepPartial) _deleteTempFile(state.outputPath);
        controller.add(
          DownloadProgress(
            phase: DownloadPhase.error,
            errorMessage: stderrBuf.toString().trim().isEmpty
                ? 'yt-dlp exited with code $code.'
                : stderrBuf.toString().trim(),
          ),
        );
        await controller.close();
        return;
      }

      // ── Phase 2: ffmpeg trim (only when start/end was requested) ──────────
      if (isTrimming) {
        final tempPath = state.outputPath;
        if (tempPath == null || !File(tempPath).existsSync()) {
          controller.add(
            const DownloadProgress(
              phase: DownloadPhase.error,
              errorMessage:
                  'Trim failed: could not locate the downloaded temp file.',
            ),
          );
          await controller.close();
          return;
        }

        controller.add(
          const DownloadProgress(
            phase: DownloadPhase.trimming,
            message: 'Trimming segment with ffmpeg…',
          ),
        );

        final tempExt = p.extension(tempPath); // includes the dot
        // Use custom filename if provided, otherwise auto-generate from
        // the video title + trim range.
        final String finalName;
        if (customFilename != null && customFilename.isNotEmpty) {
          finalName = _sanitizeFilename(customFilename);
        } else {
          final safeTitle = _sanitizeFilename(metadata.title);
          final startStr = _formatTrimRange(trimStart ?? Duration.zero);
          final endStr = _formatTrimRange(trimEnd ?? metadata.duration ?? Duration.zero);
          finalName = '$safeTitle [$startStr-$endStr]';
        }
        final finalPath = p.join(outputDir, '$finalName$tempExt');

        final ffmpegArgs = _buildFfmpegArgs(
          inputPath: tempPath,
          outputPath: finalPath,
          start: trimStart,
          end: trimEnd,
        );

        final ffResult = await _runner('ffmpeg', ffmpegArgs);

        // Rename subtitle sidecar files to match the final trimmed name,
        // then trim their content to the same time window as the video so
        // the captions stay in sync with the shorter clip.
        _renameTempSubtitleFiles(tempPath, outputDir, finalName);
        _trimSubtitleFiles(
          outputDir, finalName, trimStart ?? Duration.zero, trimEnd,
        );

        // Delete the temp video file regardless of ffmpeg outcome.
        _deleteTempFile(tempPath);

        if (state.cancelled) {
          _deleteTempFile(finalPath);
          controller.add(
            const DownloadProgress(phase: DownloadPhase.cancelled),
          );
          await controller.close();
          return;
        }

        if (ffResult.exitCode != 0) {
          final ffErr = (ffResult.stderr as String?)?.trim() ?? '';
          controller.add(
            DownloadProgress(
              phase: DownloadPhase.error,
              errorMessage: ffErr.isEmpty
                  ? 'ffmpeg exited with code ${ffResult.exitCode}. '
                    'Make sure ffmpeg is installed.'
                  : 'ffmpeg error: $ffErr',
            ),
          );
          await controller.close();
          return;
        }

        controller.add(
          DownloadProgress(
            phase: DownloadPhase.finished,
            percent: 100,
            outputPath: finalPath,
            message: 'Saved.',
          ),
        );
        await controller.close();
        return;
      }

      // ── No trim: done ─────────────────────────────────────────────────────
      controller.add(
        DownloadProgress(
          phase: DownloadPhase.finished,
          percent: 100,
          outputPath: state.outputPath,
          message: 'Saved.',
        ),
      );
      await controller.close();
    }

    run();

    return DownloadHandle._(
      stream: controller.stream,
      processFuture: processCompleter.future,
      onCancel: () => state.cancelled = true,
      onPause:  () {
        state.paused = true;
        state.pauseCallback?.call();
      },
      onResume: () {
        state.paused = false;
        state.resumeCallback?.call();
      },
    );
  }
}

// ── Module-level helpers ─────────────────────────────────────────────────────

/// Build the ffmpeg argument list for a segment cut.
/// Uses stream-copy (-c copy) so no re-encoding — fast and lossless.
/// -y overwrites without prompting; -loglevel error suppresses noise.
List<String> _buildFfmpegArgs({
  required String inputPath,
  required String outputPath,
  Duration? start,
  Duration? end,
}) {
  return [
    '-y',
    '-loglevel', 'error',
    if (start != null) ...[ '-ss', _durToFfmpeg(start) ],
    '-i', inputPath,
    // When -ss is before -i (input seeking), -to is relative to the seeked
    // position, not the original file. Use -t (duration) instead so that
    // start=1:00 end=2:00 produces a 1-minute clip, not a 2-minute one.
    if (end != null && start != null) ...[ '-t', _durToFfmpeg(end - start) ]
    else if (end != null) ...[ '-to', _durToFfmpeg(end) ],
    '-c', 'copy',
    outputPath,
  ];
}

/// Format a [Duration] as `HH:MM:SS.mmm` for ffmpeg -ss / -to arguments.
String _durToFfmpeg(Duration d) {
  final h = d.inHours.toString().padLeft(2, '0');
  final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
  final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
  final ms = (d.inMilliseconds.remainder(1000)).toString().padLeft(3, '0');
  return '$h:$m:$s.$ms';
}

/// Replace filesystem-unsafe characters with underscores.
String _sanitizeFilename(String name) {
  return name.replaceAll(RegExp(r'[<>:"/\\|?*]'), '_').trim();
}

/// Format a Duration as a compact trim-range label, e.g. `01m30s`.
String _formatTrimRange(Duration d) {
  final h = d.inHours;
  final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
  final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
  if (h > 0) return '${h}h${m}m${s}s';
  return '${m}m${s}s';
}

/// Best-effort temp file deletion. Swallows errors — if the file is already
/// gone or locked we don't want to mask the real error.
void _deleteTempFile(String? path) {
  if (path == null) return;
  try {
    final f = File(path);
    if (f.existsSync()) f.deleteSync();
  } catch (_) {}
}

/// After trimming, yt-dlp's `--write-subs` may have written sidecar files
/// like `_d4m_temp_xxx.en.srt` next to the temp video. Rename them to
/// match the final trimmed filename (e.g. `Title [01m00s-02m00s].en.srt`).
/// Swallows errors so a missing subtitle never blocks the download.
void _renameTempSubtitleFiles(
    String tempVideoPath, String outputDir, String finalBaseName) {
  try {
    final tempBase = p.basenameWithoutExtension(tempVideoPath);
    final dir = Directory(outputDir);
    if (!dir.existsSync()) return;
    for (final entity in dir.listSync()) {
      if (entity is! File) continue;
      final name = p.basename(entity.path);
      // Subtitle sidecars follow the pattern: <tempBase>.<lang>.<subExt>
      // e.g. _d4m_temp_1234.en.srt, _d4m_temp_1234.ar.vtt
      if (name.startsWith(tempBase) && name != p.basename(tempVideoPath)) {
        final suffix = name.substring(tempBase.length); // e.g. ".en.srt"
        final newPath = p.join(outputDir, '$finalBaseName$suffix');
        try {
          entity.renameSync(newPath);
        } catch (_) {}
      }
    }
  } catch (_) {}
}

/// Trim every subtitle sidecar that belongs to [finalBaseName] so only cues
/// within [start]..[end] survive, with timestamps shifted back by [start].
/// Supports SRT and VTT. Swallows all errors.
void _trimSubtitleFiles(
    String outputDir, String finalBaseName, Duration start, Duration? end) {
  try {
    final dir = Directory(outputDir);
    if (!dir.existsSync()) return;
    for (final entity in dir.listSync()) {
      if (entity is! File) continue;
      final name = p.basename(entity.path);
      if (!name.startsWith(finalBaseName)) continue;
      final ext = p.extension(name).toLowerCase();
      if (ext != '.srt' && ext != '.vtt') continue;
      try {
        final content = entity.readAsStringSync();
        final trimmed = ext == '.srt'
            ? _trimSrt(content, start, end)
            : _trimVtt(content, start, end);
        entity.writeAsStringSync(trimmed);
      } catch (_) {}
    }
  } catch (_) {}
}

/// Parse and trim an SRT subtitle string.
String _trimSrt(String content, Duration start, Duration? end) {
  final blocks = content.split(RegExp(r'\n\s*\n'));
  final buf = StringBuffer();
  int idx = 1;
  for (final block in blocks) {
    final lines = block.trim().split('\n');
    if (lines.length < 3) continue;
    // SRT timestamp line: 00:01:30,500 --> 00:01:35,000
    final match = RegExp(
      r'(\d{2}:\d{2}:\d{2}[,.]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[,.]\d{3})',
    ).firstMatch(lines[1]);
    if (match == null) continue;
    final cueStart = _parseSrtTs(match.group(1)!);
    final cueEnd = _parseSrtTs(match.group(2)!);
    if (cueStart == null || cueEnd == null) continue;
    // Skip cues entirely outside the trim window.
    if (cueEnd <= start) continue;
    if (end != null && cueStart >= end) continue;
    // Clamp and shift.
    final newStart = (cueStart < start ? Duration.zero : cueStart - start);
    final Duration newEnd;
    if (end != null && cueEnd > end) {
      newEnd = end - start;
    } else {
      newEnd = cueEnd - start;
    }
    final text = lines.sublist(2).join('\n');
    buf.writeln(idx);
    buf.writeln('${_toSrtTs(newStart)} --> ${_toSrtTs(newEnd)}');
    buf.writeln(text);
    buf.writeln();
    idx++;
  }
  return buf.toString();
}

/// Parse and trim a WebVTT subtitle string.
String _trimVtt(String content, Duration start, Duration? end) {
  final lines = content.split('\n');
  final buf = StringBuffer();
  buf.writeln('WEBVTT');
  buf.writeln();
  int i = 0;
  // Skip header lines.
  while (i < lines.length && !lines[i].contains('-->')) {
    i++;
  }
  while (i < lines.length) {
    final tsMatch = RegExp(
      r'(\d{2}:\d{2}:\d{2}\.\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}\.\d{3})',
    ).firstMatch(lines[i]);
    if (tsMatch == null) {
      i++;
      continue;
    }
    final cueStart = _parseVttTs(tsMatch.group(1)!);
    final cueEnd = _parseVttTs(tsMatch.group(2)!);
    i++;
    if (cueStart == null || cueEnd == null) continue;
    // Collect cue text.
    final textLines = <String>[];
    while (i < lines.length && lines[i].trim().isNotEmpty) {
      textLines.add(lines[i]);
      i++;
    }
    // Skip blank separator lines.
    while (i < lines.length && lines[i].trim().isEmpty) {
      i++;
    }
    if (cueEnd <= start) continue;
    if (end != null && cueStart >= end) continue;
    final newStart = (cueStart < start ? Duration.zero : cueStart - start);
    final Duration newEnd;
    if (end != null && cueEnd > end) {
      newEnd = end - start;
    } else {
      newEnd = cueEnd - start;
    }
    buf.writeln('${_toVttTs(newStart)} --> ${_toVttTs(newEnd)}');
    for (final l in textLines) {
      buf.writeln(l);
    }
    buf.writeln();
  }
  return buf.toString();
}

Duration? _parseSrtTs(String s) {
  // 00:01:30,500
  final m = RegExp(r'(\d{2}):(\d{2}):(\d{2})[,.](\d{3})').firstMatch(s);
  if (m == null) return null;
  return Duration(
    hours: int.parse(m.group(1)!),
    minutes: int.parse(m.group(2)!),
    seconds: int.parse(m.group(3)!),
    milliseconds: int.parse(m.group(4)!),
  );
}

Duration? _parseVttTs(String s) {
  // 00:01:30.500
  final m = RegExp(r'(\d{2}):(\d{2}):(\d{2})\.(\d{3})').firstMatch(s);
  if (m == null) return null;
  return Duration(
    hours: int.parse(m.group(1)!),
    minutes: int.parse(m.group(2)!),
    seconds: int.parse(m.group(3)!),
    milliseconds: int.parse(m.group(4)!),
  );
}

String _toSrtTs(Duration d) {
  final h = d.inHours.toString().padLeft(2, '0');
  final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
  final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
  final ms = d.inMilliseconds.remainder(1000).toString().padLeft(3, '0');
  return '$h:$m:$s,$ms';
}

String _toVttTs(Duration d) {
  final h = d.inHours.toString().padLeft(2, '0');
  final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
  final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
  final ms = d.inMilliseconds.remainder(1000).toString().padLeft(3, '0');
  return '$h:$m:$s.$ms';
}


/// Lives outside [YtDlpService.download] only because Dart doesn't let a
/// closure capture local variables by reference for assignment.
class _DownloadState {
  bool cancelled = false;
  bool paused    = false;
  String? outputPath;
  double? lastPercent;

  /// Set by [YtDlpService.download] once the stdout subscription exists.
  void Function()? pauseCallback;
  void Function()? resumeCallback;
}

/// Handle returned from [YtDlpService.download]. Lets the controller listen
/// for progress events and ask the underlying process to terminate or pause.
class DownloadHandle {
  DownloadHandle._({
    required this.stream,
    required this.processFuture,
    required void Function() onCancel,
    required void Function() onPause,
    required void Function() onResume,
  })  : _onCancel = onCancel,
        _onPause  = onPause,
        _onResume = onResume;

  /// One [DownloadProgress] per stdout line + one terminal phase event
  /// (finished / error / cancelled). Closes when the subprocess exits.
  final Stream<DownloadProgress> stream;

  /// Completes once the underlying [Process] is actually started. If yt-dlp
  /// is missing on PATH, completes with an error instead.
  final Future<Process> processFuture;

  final void Function() _onCancel;
  final void Function() _onPause;
  final void Function() _onResume;
  bool _cancelled = false;
  bool _paused    = false;

  bool get isCancelled => _cancelled;
  bool get isPaused    => _paused;

  /// Suspend the stdout read loop so yt-dlp stalls naturally.
  void pause() {
    if (_cancelled || _paused) return;
    _paused = true;
    _onPause();
  }

  /// Resume reading stdout — yt-dlp resumes downloading immediately.
  void resume() {
    if (_cancelled || !_paused) return;
    _paused = false;
    _onResume();
  }

  /// Send SIGTERM (or kill on Windows) to the running yt-dlp process. The
  /// stream will then emit a [DownloadPhase.cancelled] event and close.
  Future<void> cancel() async {
    if (_cancelled) return;
    _cancelled = true;
    // If paused, resume the subscription first so the process exit is read.
    if (_paused) {
      _paused = false;
      _onResume();
    }
    _onCancel();
    try {
      final p = await processFuture;
      p.kill(ProcessSignal.sigterm);
    } catch (_) {
      // Process never started; nothing to kill.
    }
  }
}

/// Thrown by [YtDlpService.fetchMetadata] for any failure (process missing,
/// non-zero exit, JSON parse failure). Message is safe to show to the user.
class YtDlpException implements Exception {
  YtDlpException(this.message);
  final String message;
  @override
  String toString() => message;
}

/// Parse a single line of yt-dlp `--newline` stdout. Returns null if the line
/// isn't a recognised progress / status update.
///
/// Lines we handle:
/// - `[download]   1.5% of  100.00MiB at  2.50MiB/s ETA 00:39`
/// - `[download] 100% of   23.86MiB in 00:08 at 2.84MiB/s`
/// - `[download] Destination: /path/to/file.mp4`
/// - `[Merger] Merging formats into "/path/to/file.mp4"`
/// - `[ExtractAudio] Destination: /path/to/file.m4a`
@visibleForTesting
DownloadProgress? parseProgressLine(String line) {
  final trimmed = line.trim();
  if (trimmed.isEmpty) return null;

  // "Destination" lines tell us the final filename.
  final dest = RegExp(r'^\[(?:download|ExtractAudio)\]\s+Destination:\s+(.+)$')
      .firstMatch(trimmed);
  if (dest != null) {
    return DownloadProgress(
      phase: DownloadPhase.downloading,
      outputPath: dest.group(1)!.trim(),
      message: 'Saving to ${dest.group(1)!.trim()}',
    );
  }

  final merger = RegExp(r'^\[Merger\]\s+Merging formats into\s+"(.+)"$')
      .firstMatch(trimmed);
  if (merger != null) {
    return DownloadProgress(
      phase: DownloadPhase.downloading,
      percent: 100,
      outputPath: merger.group(1)!,
      message: 'Merging audio + video…',
    );
  }

  // Progress line. Be liberal in what we accept since yt-dlp's spacing varies.
  final progress = RegExp(
    r'^\[download\]\s+'
    r'(\d+(?:\.\d+)?)%'
    r'\s+of\s+~?\s*([\d.]+)\s*([KMGTP]?i?B)'
    r'(?:\s+at\s+([\d.]+|Unknown)\s*([KMGTP]?i?B/s)?)?'
    r'(?:\s+ETA\s+(\S+))?',
  ).firstMatch(trimmed);
  if (progress != null) {
    final percent = double.tryParse(progress.group(1)!);
    final totalAmount = double.tryParse(progress.group(2)!);
    final totalUnit = progress.group(3);
    final speedAmount = double.tryParse(progress.group(4) ?? '');
    final speedUnit = progress.group(5);
    final etaStr = progress.group(6);
    return DownloadProgress(
      phase: DownloadPhase.downloading,
      percent: percent,
      totalBytes: totalAmount != null && totalUnit != null
          ? _bytesFromSize(totalAmount, totalUnit)
          : null,
      speedBytesPerSecond: speedAmount != null && speedUnit != null
          ? _bytesFromSize(speedAmount, speedUnit.replaceAll('/s', ''))
              .toDouble()
          : null,
      eta: etaStr != null ? _parseEta(etaStr) : null,
    );
  }

  return null;
}

int _bytesFromSize(double amount, String unit) {
  // Both binary (KiB / MiB / ...) and decimal (KB / MB / ...) forms appear in
  // yt-dlp output depending on version / postprocessor. Treat them the same
  // way — close enough for a progress UI.
  const multipliers = <String, int>{
    'B': 1,
    'KB': 1024,
    'MB': 1024 * 1024,
    'GB': 1024 * 1024 * 1024,
    'TB': 1024 * 1024 * 1024 * 1024,
    'KiB': 1024,
    'MiB': 1024 * 1024,
    'GiB': 1024 * 1024 * 1024,
    'TiB': 1024 * 1024 * 1024 * 1024,
  };
  return (amount * (multipliers[unit] ?? 1)).round();
}

Duration? _parseEta(String s) {
  final parts = s.split(':');
  try {
    if (parts.length == 2) {
      return Duration(minutes: int.parse(parts[0]), seconds: int.parse(parts[1]));
    } else if (parts.length == 3) {
      return Duration(
        hours: int.parse(parts[0]),
        minutes: int.parse(parts[1]),
        seconds: int.parse(parts[2]),
      );
    }
  } on FormatException {
    return null;
  }
  return null;
}

Future<ProcessResult> _defaultRunner(String exe, List<String> args) =>
    Process.run(exe, args, stdoutEncoding: utf8, stderrEncoding: utf8);

Future<Process> _defaultSpawner(String exe, List<String> args) =>
    Process.start(exe, args, runInShell: false);
